import {StyleSheet, Dimensions, Platform} from 'react-native';
import Scale from '../../Components/Scale';

const {width, height} = Dimensions.get('screen');

export const styles = StyleSheet.create({
  mainViewStyle: {flex: 1, backgroundColor: '#EAE9EE'},
  firstStyle: {
    flex: 0.8,
    alignItems: 'center',
  },
  productTextStyle: {
    fontSize: Scale(15),
    marginVertical: Scale(10),
    alignSelf: 'flex-start',
    marginLeft: Scale(25),
  },
  productTextinputStyle: {
    padding: '3%',
    fontSize: Scale(20),
    color: '#000',
    display: 'flex',
    width: '90%',
    height: height * 0.07,
    backgroundColor: '#D7D7D7',
    borderRadius: Scale(13),
    borderWidth: Scale(0.8),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  priceTextStyle: {
    fontSize: Scale(15),
    marginVertical: Scale(10),
    alignSelf: 'flex-start',
    marginLeft: Scale(25),
  },
  priceTextInputStyle: {
    padding: '3%',
    fontSize: Scale(20),
    color: '#000',
    display: 'flex',
    width: '90%',
    height: height * 0.07,
    backgroundColor: '#D7D7D7',
    borderRadius: Scale(13),
    borderWidth: Scale(0.8),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  descriptionTextInputStyle: {
    padding: '3%',
    fontSize: Scale(20),
    color: '#000',
    display: 'flex',
    width: '90%',
    height: height * 0.12,
    backgroundColor: '#D7D7D7',
    borderRadius: Scale(13),
    borderWidth: Scale(0.8),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  imageLinkStyle: {
    padding: '3%',
    fontSize: Scale(20),
    marginVertical: Scale(20),
    color: '#000',
    display: 'flex',
    width: '90%',
    height: height * 0.07,
    backgroundColor: '#D7D7D7',
    borderRadius: Scale(13),
    borderWidth: Scale(0.8),
    alignItems: 'center',
  },
  secondStyle: {
    flex: 0.1,
    //   backgroundColor: '#EAE9EE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButtonStyle: {
    borderRadius: Scale(15),
    paddingHorizontal: Scale(10),
    marginHorizontal: Scale(10),
    borderWidth: Scale(0.5),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: Scale(50),
    backgroundColor: '#000',
  },
  addProductTextStyle: {fontSize: Scale(20), color: '#fff'},
  categoryChipStyle: {
    borderRadius: Scale(15),
    paddingHorizontal: Scale(10),
    marginHorizontal: Scale(10),
    borderWidth: Scale(1),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: Scale(50),
    marginBottom: Scale(70),
    padding: Platform.OS === 'ios' ? Scale(10) : Scale(10),
  },
});
